-- Baseline migration reflecting the schema as of this commit.
--
-- IMPORTANT: this file was hand-authored, not generated by `prisma migrate
-- dev` against a live database — this sandbox has no network access to a
-- Postgres instance or to Prisma's engine binaries. It was written to
-- exactly match prisma/schema.prisma and Prisma's normal generated SQL
-- conventions, but has NOT been executed or verified against a real
-- database. Review it (or regenerate it properly, see README "Migration
-- strategy") before running it against production.
--
-- If your Neon database was already synchronized with `prisma db push`
-- (as this project's was), do NOT run this migration normally — it would
-- try to CREATE TABLE on tables that already exist and fail. Instead,
-- mark it as already applied without running its SQL:
--
--   npx prisma migrate resolve --applied 0_baseline
--
-- Every migration created after this one (via `prisma migrate dev`) will
-- then apply normally on top of the already-synced schema.

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'MEMBER');

-- CreateEnum
CREATE TYPE "ProviderType" AS ENUM ('LOCAL_DOCKER', 'VERCEL', 'RAILWAY', 'RENDER', 'FLY_IO', 'KUBERNETES');

-- CreateEnum
CREATE TYPE "PrState" AS ENUM ('OPEN', 'CLOSED', 'MERGED');

-- CreateEnum
CREATE TYPE "DeploymentStatus" AS ENUM ('QUEUED', 'PROVISIONING', 'DEPLOYING', 'HEALTH_CHECK', 'LIVE', 'UPDATING', 'FAILED', 'STOPPED', 'EXPIRED');

-- CreateTable
CREATE TABLE "organizations" (
    "id" TEXT NOT NULL,
    "githubOrgId" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "apiKeyHash" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "githubUserId" BIGINT NOT NULL,
    "login" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'MEMBER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "repositories" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "githubRepoId" BIGINT NOT NULL,
    "fullName" TEXT NOT NULL,
    "installationId" BIGINT NOT NULL,
    "allowed" BOOLEAN NOT NULL DEFAULT false,
    "allowForkPrs" BOOLEAN NOT NULL DEFAULT false,
    "defaultProvider" "ProviderType" NOT NULL DEFAULT 'LOCAL_DOCKER',
    "secretAllowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "previewAuthRequired" BOOLEAN NOT NULL DEFAULT false,
    "webhookSecretRef" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "repositories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pull_requests" (
    "id" TEXT NOT NULL,
    "repoId" TEXT NOT NULL,
    "githubPrNumber" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "authorLogin" TEXT NOT NULL,
    "isFork" BOOLEAN NOT NULL DEFAULT false,
    "needsApproval" BOOLEAN NOT NULL DEFAULT false,
    "baseSha" TEXT NOT NULL,
    "headSha" TEXT NOT NULL,
    "state" "PrState" NOT NULL DEFAULT 'OPEN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pull_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deployments" (
    "id" TEXT NOT NULL,
    "prId" TEXT NOT NULL,
    "provider" "ProviderType" NOT NULL,
    "status" "DeploymentStatus" NOT NULL DEFAULT 'QUEUED',
    "url" TEXT,
    "commitSha" TEXT NOT NULL,
    "failureReason" TEXT,
    "demoMode" BOOLEAN NOT NULL DEFAULT true,
    "healthCheckAttempts" INTEGER NOT NULL DEFAULT 0,
    "lastHealthCheckAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "deployments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deployment_events" (
    "id" TEXT NOT NULL,
    "deploymentId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "deployment_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" TEXT NOT NULL,
    "githubDeliveryId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "payloadHash" TEXT NOT NULL,
    "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "organizations_githubOrgId_key" ON "organizations"("githubOrgId");
-- CreateIndex
CREATE UNIQUE INDEX "organizations_apiKeyHash_key" ON "organizations"("apiKeyHash");

-- CreateIndex
CREATE UNIQUE INDEX "users_githubUserId_key" ON "users"("githubUserId");
-- CreateIndex
CREATE INDEX "users_orgId_idx" ON "users"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "repositories_githubRepoId_key" ON "repositories"("githubRepoId");
-- CreateIndex
CREATE INDEX "repositories_orgId_idx" ON "repositories"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "pull_requests_repoId_githubPrNumber_key" ON "pull_requests"("repoId", "githubPrNumber");
-- CreateIndex
CREATE INDEX "pull_requests_repoId_idx" ON "pull_requests"("repoId");

-- CreateIndex
CREATE INDEX "deployments_prId_idx" ON "deployments"("prId");
-- CreateIndex
CREATE INDEX "deployments_status_idx" ON "deployments"("status");

-- CreateIndex
CREATE INDEX "deployment_events_deploymentId_idx" ON "deployment_events"("deploymentId");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_deliveries_githubDeliveryId_key" ON "webhook_deliveries"("githubDeliveryId");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "repositories" ADD CONSTRAINT "repositories_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pull_requests" ADD CONSTRAINT "pull_requests_repoId_fkey" FOREIGN KEY ("repoId") REFERENCES "repositories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_prId_fkey" FOREIGN KEY ("prId") REFERENCES "pull_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deployment_events" ADD CONSTRAINT "deployment_events_deploymentId_fkey" FOREIGN KEY ("deploymentId") REFERENCES "deployments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
