-- Multi-tenant auth: replaces User's direct single-org FK with a
-- Membership join table (a user may belong to multiple orgs), and adds
-- the tables needed for GitHub OAuth sessions.
--
-- Same honesty note as 0_baseline: hand-authored to match
-- prisma/schema.prisma exactly, NOT generated by `prisma migrate dev`
-- against a live database from this environment (no network access to
-- Postgres or Prisma's engine binaries here). Review before applying to
-- production; run `prisma migrate diff` against your real DB first to
-- confirm this is what's actually needed, same as documented in the
-- README's migration strategy for the baseline.
--
-- SAFE TO APPLY: the `users` table currently has zero application code
-- depending on it (verified by inspection before this migration was
-- written -- `User`/`Role` were defined in the schema but never queried
-- anywhere in src/), so dropping and recreating its shape here does not
-- touch any data that's actually in use. If your production `users` table
-- somehow has real rows you care about, back up first and adapt this
-- migration instead of running it as-is.

-- DropForeignKey (old User -> Organization direct link)
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_orgId_fkey";

-- DropIndex
DROP INDEX IF EXISTS "users_orgId_idx";

-- AlterTable: drop the old direct org link, add avatarUrl
ALTER TABLE "users" DROP COLUMN IF EXISTS "orgId";
ALTER TABLE "users" DROP COLUMN IF EXISTS "role";
ALTER TABLE "users" ADD COLUMN "avatarUrl" TEXT;

-- CreateTable
CREATE TABLE "memberships" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'MEMBER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "memberships_userId_orgId_key" ON "memberships"("userId", "orgId");
-- CreateIndex
CREATE INDEX "memberships_userId_idx" ON "memberships"("userId");
-- CreateIndex
CREATE INDEX "memberships_orgId_idx" ON "memberships"("orgId");

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "revoked_sessions" (
    "sid" TEXT NOT NULL,
    "revokedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "revoked_sessions_pkey" PRIMARY KEY ("sid")
);

-- CreateIndex
CREATE INDEX "revoked_sessions_expiresAt_idx" ON "revoked_sessions"("expiresAt");

-- CreateTable
CREATE TABLE "one_time_exchange_codes" (
    "code" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "usedAt" TIMESTAMP(3),

    CONSTRAINT "one_time_exchange_codes_pkey" PRIMARY KEY ("code")
);

-- CreateIndex
CREATE INDEX "one_time_exchange_codes_expiresAt_idx" ON "one_time_exchange_codes"("expiresAt");
